### ISSUE TITLE
RepositoryConnection.export(handler, graphs) ignores contexts

### ISSUE THREAD

**Issue by elky87** [marklogic/marklogic-rdf4j#18]
See code
```

 public void export(RDFHandler handler, Resource... contexts) throws RepositoryException, RDFHandlerException {
        exportStatements(null, null, null, true, handler);
    }
```
This causes quite some problems because when we use export the whole store gets exported.

**Comment by akshaysonvane** [comment]
Hi @elky87, thanks for getting it reported. Also, the includeInferred parameter should be changed to false as per [spec](http://docs.rdf4j.org/javadoc/2.2/org/eclipse/rdf4j/repository/RepositoryConnection.html#export-org.eclipse.rdf4j.rio.RDFHandler-org.eclipse.rdf4j.model.Resource...-).
