### ISSUE TITLE
http://central.maven.org/maven2/artifact/com.marklogic/marklogic-rdf4j/1.1.0 results in 404

### ISSUE THREAD

**Issue by aslack19** [marklogic/marklogic-rdf4j#23]
The docs are incorrect.  The mvn link results in a 404 so either the docs are wrong and need updating or the artifact needs publishing.  Thanks.

**Comment by grechaw** [comment]
Hi @aslack19 this release has actually not happened yet.  I'm not sure why the documentation is already pointing there -- perhaps on develop branch all the ducks are getting lined up. 
I know on other projects we've made rc branches to contain release-specific changes, perhaps that should also be done here to avoid the confusion.

**Comment by grechaw** [comment]
Hi @aslack19 , I've made the default branch 'master' so that folks won't run into this issue again.  So the current latest release is 1.0.0, which is in deed in mvn central.  Check back, we will release 1.1.0 in a couple of weeks (no further changes to develop branch anticipated)
