### ISSUE TITLE
Fire CPF for triples loaded in a transaction i.e. load triples in a given directory path

### ISSUE THREAD

**Issue by RavinderSinghMaan** [marklogic/marklogic-rdf4j#26]
Hi 

We need to fire CPF pipeline when triples are loaded so that further processing can be done on the loaded data and reports can be generated or some other systems can be notfied.  In a transaction, multiple triples can be loaded but we need to fire CPF only once after the transaction commits. As you might know to fire the CPF there are 2 options collection or directory.  At the moment there is no way to specify a directory for the triples loaded through this API. So we have been using collection/graph to fire CPF i.e. in every transaction we write one extra triple which gets inserted into a graph/collection and We have configured CPF pipeline where domain is the collection to which single triple is written. This approach has a problem as when lots of concurrent transactions are writing to same graph/collection it causes contention issues. So what I was thinking will be really useful is to have a method like below in `MarkLogicRepositoryConnection` 

`public void add(Iterable<? extends Statement> statements, String directoryBasPath, Resource... contexts)` 

Above would load all the statements under given directoryBasPath. Low level xquery functions like `sem:rdf-load` give the ability to specify the directory and if same ability is given through this API it will be useful in other ways as well. 

Also, I think it will useful if a method is added to `MarkLogicRepositoryConnection` to get underlying com.marklogic.client.DatabaseClient . This means if I have to do other operations apart from semantic data I can do it within the same transaction. I know it is possible to get the current transaction using `getTransaction()` and then transaction id can be used to achieve the same but I think it will be useful to get hold of  `com.marklogic.client.DatabaseClient`. What do you guys think?

Thanks
Ravinder

**Comment by RavinderSinghMaan** [comment]
@grechaw do you have any opinion on this?

**Comment by grechaw** [comment]
Your use case doesn't sound as though it's slated for success, but the enhancement request aside from that is tractable.  getting the DatabaseClient, too, is straightforward.
Multi-statement transactions in general are a pretty blunt instrument, and as you already know you're pushing the envelope pretty hard with triples + transactions.

**Comment by grechaw** [comment]
@akshaysonvane  can you decompose this issue into it's two enhancement requests (access to db client and adding a directory param.)  Since you're reworking add() anyway, we have the opportunity to control URIs from the client side.

**Comment by RavinderSinghMaan** [comment]
@grechaw It is interesting you say "Your use case doesn't sound as though it's slated for success". So what is the best way to do it?

**Comment by grechaw** [comment]
Well, what I'm wary of, and I can't back it up with much, is that multi-statement transactions are a pretty heavyweight tool.  The contention you describe seems like it will plague you regardless.  Can you describe the use case in detail?

**Comment by grechaw** [comment]
I think you hit the 'close and comment' button by mistake @RavinderSinghMaan ?

**Comment by RavinderSinghMaan** [comment]
@grechaw Sorry my bad.

Coming back to our original discussion.This was all originally implemented by experts. Even I have some concerns but we are fixing the problems as we see them. I have a plan to move away from multistatement transactions but will do a proper performance test first and then will move away if required.

**Comment by akshaysonvane** [comment]
Commit https://github.com/marklogic/marklogic-rdf4j/commit/1489bc39779f7fd4773bdc036f90713718397d46 adds access to DatabaseClient.

**Comment by akshaysonvane** [comment]
Split the issue into two parts.
Access to DatabaseClient is added and thus closing this issue.
Feature request to load triples in a given directory path can be tracked via https://github.com/marklogic/marklogic-rdf4j/issues/42
