### ISSUE TITLE
Incomplete Support statement

### ISSUE THREAD

**Issue by popzip** [marklogic/marklogic-rdf4j#31]
Current Support statement missing some language about intended use with MarkLogic Server, in production, encouraging feedback without promise of timeframe, etc. See other MarkLogic projects - like https://github.com/marklogic/java-client-api - would be good to have consistency.

**Comment by akshaysonvane** [comment]
Thanks, @popzip for creating the issue.
[Support Statement](https://github.com/marklogic/marklogic-rdf4j/blob/develop/README.md) has been updated.
