### ISSUE TITLE
SPARQLRepositoryTest fails when targeting AWS node (vs localhost)

### ISSUE THREAD

**Issue by laquereric** [marklogic/marklogic-rdf4j#38]
Test com.marklogic.semantics.rdf4j.SPARQLRepositoryTest on develop branch fails when using AWS node:

COMMAND: ./gradlew :marklogic-rdf4j:test
.....
com.marklogic.semantics.rdf4j.SPARQLRepositoryTest > testSPARQLRepositoryWithMarkLogic STARTED

com.marklogic.semantics.rdf4j.SPARQLRepositoryTest > testSPARQLRepositoryWithMarkLogic FAILED
org.eclipse.rdf4j.repository.RepositoryException at SPARQLRepositoryTest.java:64
Caused by: org.eclipse.rdf4j.query.UpdateExecutionException at SPARQLRepositoryTest.java:64
Caused by: org.eclipse.rdf4j.http.protocol.UnauthorizedException at SPARQLRepositoryTest.java:64

**Comment by laquereric** [comment]
password for AWS is not 'admin'... 
So I tried a fix:
marklogic-rdf4j\marklogic-rdf4j\src\test\java\com\marklogic\semantics\rdf4j\SPARQLRepositoryTest.java
line 52:      sr.setUsernameAndPassword(user,password);

All tests pass!

**Comment by akshaysonvane** [comment]
Thanks for getting it reported @laquereric 
Closing the issue as it's fixed via PR https://github.com/marklogic/marklogic-rdf4j/pull/40
