### ISSUE TITLE
BNodes skolmization causing data corruption or read failures

### ISSUE THREAD

**Issue by RavinderSinghMaan** [marklogic/marklogic-rdf4j#39]
In the Util.java in the skolemize function `s.toString()` is used which means for bnodes it ends up generating skolemized IRI of the form ` <http://marklogic.com/semantics/blank/_:node1cfo92v6rx1>` . Note `_:` in the IRI. This means when ML serialise the triple for reads it gives back `_:bnode_:node1cfo92v6rx1`. Note `_:` twice. This mean resouce cannot be described or read back because Rio parser fails. So Instead of using `s.toString` it should use`s.stringValue()` . 

Below is the test for same
```
    @Test
    public void testBNodeSkolmization() throws Exception
    {
        ValueFactory vf = conn.getValueFactory();
        Resource context1 = vf.createIRI("http://marklogic.com/test/context1");
        IRI alice = vf.createIRI("http://example.org/people/alice");
        IRI name = vf.createIRI("http://example.org/ontology/name");
        BNode alicesName = vf.createBNode();
        Statement st1 = vf.createStatement(alice, name, alicesName);
        conn.add(st1, context1);
        final GraphQueryResult evaluate = conn.prepareGraphQuery("DESCRIBE <http://example.org/people/alice>").evaluate();

        Assert.assertTrue(evaluate.hasNext());
    }

```

Another test which fails due to Rio parser . Data can go in ML but can't be read back

```
    @Test
    public void testBNodeSkolmization() throws Exception
    {
        ValueFactory vf = conn.getValueFactory();
        Resource context1 = vf.createIRI("http://marklogic.com/test/context1");
        IRI alice = vf.createIRI("http://example.org/people/alice");

        final Model model = Rio.parse(new StringReader("<"+alice+"> <http://www.perceive.net/schemas/relationship/enemyOf> _:b1 ."), "", RDFFormat.TURTLE);

        conn.add(model, context1);

        final GraphQueryResult evaluate = conn.prepareGraphQuery("DESCRIBE <http://example.org/people/alice>").evaluate();

        Assert.assertTrue(evaluate.hasNext());
    }
```

**Comment by RavinderSinghMaan** [comment]
@grechaw @akshaysonvane any thoughts?

**Comment by grechaw** [comment]
That certainly is suspicious looking.  I don't understand how skolemization affects the two tests you've provided, so take a look at repro.

If the solution is as simple as you suggest, then it seems it should be easily fixable in a maintenance release.

**Comment by RavinderSinghMaan** [comment]
@grechaw for the first test case solution is simple. But the second one is going to be tricky as the problem is in Rio parser itself.

**Comment by grechaw** [comment]
Thanks @RavinderSinghMaan , that makes sense

**Comment by akshaysonvane** [comment]
BNode Skolemization issue to be fixed via PR https://github.com/marklogic/marklogic-rdf4j/pull/40
The issue with RIO parser is in RDF4J library and can be tracked via https://github.com/eclipse/rdf4j/issues/1041

**Comment by RavinderSinghMaan** [comment]
@akshaysonvane @grechaw Thanks. Fix looks good. A few questions/points. 

- Can we also upgrade to the latest version of MarkLogic Java client API? 
- When can you release these fixes?
- IMHO best technique for skolmization will be to use same algo which is used on ML side when SPARQL UPDATE is used and query contains blank nodes. In ML blanks nodes are converted to long numbers and then prefixed with URI. Do you guys know what algo is used in ML?
- IMHO https://github.com/marklogic/marklogic-sesame/issues/364 should not be done as same is not possible with SPARQL. This can cause problems in future.

Thanks
Ravinder

**Comment by akshaysonvane** [comment]
Split the issue into two parts.
Bnode skolemization issue is fixed and thus closing this issue.
The issue with RIO parser can be tracked via https://github.com/marklogic/marklogic-rdf4j/issues/43
